name: Jumpcore
author: Fooble
version: 0.1-ALPHA
api-version: 1.20

main: dev.fooble.jumpcore.Jumpcore

commands:
  jumpcore:
    usage: /jumpcore
    description: The main command for the plugin.
    aliases:
      - jumpandrun